// Generated by LiveScript 1.2.0
(function(){
  var Debugger, PermitRegistry, PermitMatcher, RuleRepo, PermitApplier, Observable, Activation, Permit;
  Debugger = require('../util').Debugger;
  PermitRegistry = require('./registry').PermitRegistry;
  PermitMatcher = require('./matcher').PermitMatchController;
  RuleRepo = require('../rule').repo.RuleRepo;
  PermitApplier = require('./rule').PermitRuleApplier;
  Observable = require('../mixin').Observable;
  Activation = require('../mixin').Activation;
  module.exports = Permit = (function(){
    Permit.displayName = 'Permit';
    var prototype = Permit.prototype, constructor = Permit;
    importAll$(prototype, arguments[0]);
    importAll$(prototype, arguments[1]);
    importAll$(prototype, arguments[2]);
    function Permit(name, description, debugging){
      this.name = name;
      this.description = description != null ? description : '';
      this.debugging = debugging;
      this.matchEnabled = false;
      if (this.activate && this.autoActivate) {
        this.activate();
      }
      this._register();
      this.init();
      this;
    }
    Permit.registry || (Permit.registry = new PermitRegistry);
    prototype.repo = function(){
      return this._repo || (this._repo = new RuleRepo(this.name));
    };
    prototype.applier = function(){
      return this._applier || (this._applier = new PermitApplier(this, this.debugging));
    };
    prototype.permitMatcher = function(accessRequest){
      return new PermitMatcher(this, accessRequest, this.debugging);
    };
    prototype.rules = function(){};
    prototype._register = function(){
      this.debug('register permit', this);
      return this.registry().register(this);
    };
    prototype._unregister = function(){
      return this.registry().unregister(this);
    };
    Permit.get = function(name){
      return constructor.registry.get(name);
    };
    prototype.registry = function(){
      return constructor.registry;
    };
    Permit.enableMatch = function(){
      return this.matchEnabled = true;
    };
    Permit.disableMatch = function(){
      return this.matchEnabled = false;
    };
    prototype.match = function(accessRequest){
      if (this.matchEnabled) {
        return this.permitMatcher(accessRequest).match();
      }
    };
    prototype.init = function(){
      this.debug('permit init');
      this.applier.apply('static');
      return this;
    };
    prototype.clean = function(){
      this.repo().clean();
      return this.applier().clean();
    };
    prototype.canRules = function(){
      return this.repo().canRules();
    };
    prototype.cannotRules = function(){
      return this.repo().cannotRules();
    };
    return Permit;
  }(Activation, Observable, Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
