// Generated by LiveScript 1.2.0
(function(){
  var Debugger, RuleRepo, PermitRuleApplier, PermitRegistry, PermitMatcher, PermitAllower, Permit, toString$ = {}.toString;
  Debugger = require('../util').Debugger;
  module.exports = Permit = (function(){
    Permit.displayName = 'Permit';
    var prototype = Permit.prototype, constructor = Permit;
    importAll$(prototype, arguments[0]);
    function Permit(name, description, debugging){
      this.name = name;
      this.description = description != null ? description : '';
      this.debugging = debugging;
      RuleRepo = require('../rule').repo.RuleRepo;
      PermitRuleApplier = require('./rule').PermitRuleApplier;
      PermitRegistry = require('./registry').PermitRegistry;
      PermitMatcher = require('./matcher').PermitMatchController;
      PermitAllower = require('../allower').PermitAllower;
      Permit.registry || (Permit.registry = new PermitRegistry);
      this.registry().registerPermit(this);
      this.ruleRepo = new RuleRepo(this.name);
      this.ruleApplier = new PermitRuleApplier(this, this.debugging);
      this.permitAllower = new PermitAllower(this.ruleRepo);
      this;
    }
    Permit.enableMatch = function(){
      return this.matchEnabled = true;
    };
    Permit.disableMatch = function(){
      return this.matchEnabled = false;
    };
    prototype.permitMatcher = function(){
      return new PermitMatcher(this, this.accessRequest, this.debugging);
    };
    prototype.match = function(){
      if (!this.permitMatcher) {
        return true;
      }
      if (this.matchEnabled) {
        return this.permitMatcher.match();
      }
    };
    prototype.registry = function(){
      return constructor.registry;
    };
    Permit.get = function(name){
      return PermitRegistry.get(name);
    };
    prototype.init = function(){
      this.debug('permit init');
      this.ruleApplier.applyRules('static');
      return this;
    };
    prototype.clean = function(){
      this.ruleRepo.clean();
      return this.ruleApplier.clean();
    };
    prototype.use = function(obj){
      if (toString$.call(obj).slice(8, -1) === 'Function') {
        obj = obj();
      }
      if (toString$.call(obj).slice(8, -1) === 'Object') {
        return import$(this, obj);
      } else {
        throw Error("Can only extend permit with an Object, was: " + toString$.call(obj).slice(8, -1));
      }
    };
    prototype.rules = function(){};
    prototype.canRules = function(){
      return this.ruleRepo.canRules;
    };
    prototype.cannotRules = function(){
      return this.ruleRepo.cannotRules;
    };
    return Permit;
  }(Debugger));
  import$(Permit, Debugger);
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
