// Generated by LiveScript 1.2.0
(function(){
  var Debugger, RuleRepo, PermitRuleApplier, PermitRegistry, UsePermitMatcher, PermitAllower, Permit, toString$ = {}.toString;
  Debugger = require('../util').Debugger;
  /*
  
  
  
  
  matchers        = require '../access_request' .matcher
  
  UserMatcher     = matchers.UserMatcher
  SubjectMatcher  = matchers.SubjectMatcher
  ActionMatcher   = matchers.ActionMatcher
  ContextMatcher  = matchers.ContextMatcher
  AccessMatcher   = matchers.AccessMatcher
  
  PermitMatch     = require './permit_match_mixin'
  PermitAllow     = require './permit_allow_mixin'
  
  PermitCompileStatic = require './permit_compile_static'
  */
  module.exports = Permit = (function(){
    Permit.displayName = 'Permit';
    var prototype = Permit.prototype, constructor = Permit;
    importAll$(prototype, arguments[0]);
    function Permit(name, description, debugging){
      this.name = name;
      this.description = description != null ? description : '';
      this.debugging = debugging;
      RuleRepo = require('../rule').repo.RuleRepo;
      PermitRuleApplier = require('./rule').PermitRuleApplier;
      PermitRegistry = require('./registry').PermitRegistry;
      UsePermitMatcher = require('./matcher').UsePermitMatcher;
      PermitAllower = require('../allower').PermitAllower;
      Permit.registry || (Permit.registry = new PermitRegistry);
      this.registry().registerPermit(this);
      this.ruleRepo = new RuleRepo(this.name);
      this.ruleApplier = new PermitRuleApplier(this, this.debugging);
      this.usePermitMatcher = new UsePermitMatcher(this, this.accessRequest);
      this.permitAllower = new PermitAllower(this.ruleRepo);
      this;
    }
    prototype.registry = function(){
      return constructor.registry;
    };
    Permit.get = function(name){
      return PermitRegistry.get(name);
    };
    prototype.init = function(){
      this.debug('permit init');
      this.ruleApplier.applyRules('static');
      this.configureMatchers();
      return this;
    };
    prototype.configureMatchers = function(){
      var PermitMatchesCompiler;
      PermitMatchesCompiler = require('./matches').PermitMatchesCompiler;
      return new PermitMatchesCompiler(this, this.debugging).compileMatchers();
    };
    prototype.clean = function(){
      this.ruleRepo.clean();
      return this.ruleApplier.clean();
    };
    prototype.use = function(obj){
      if (toString$.call(obj).slice(8, -1) === 'Function') {
        obj = obj();
      }
      if (toString$.call(obj).slice(8, -1) === 'Object') {
        return import$(this, obj);
      } else {
        throw Error("Can only extend permit with an Object, was: " + toString$.call(obj).slice(8, -1));
      }
    };
    prototype.rules = function(){};
    prototype.canRules = function(){
      return this.ruleRepo.canRules;
    };
    prototype.cannotRules = function(){
      return this.ruleRepo.cannotRules;
    };
    return Permit;
  }(Debugger));
  import$(Permit, Debugger);
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
