// Generated by LiveScript 1.2.0
(function(){
  var lo, Permit, toString$ = {}.toString;
  lo = require('../util/lodash_lite');
  Permit = require('../permit');
  module.exports = function(baseClazz, name, baseObj, debug){
    var permit;
    if (toString$.call(baseClazz).slice(8, -1) === 'String') {
      baseObj = name;
      name = baseClazz;
      baseClazz = Permit;
    }
    permit = new baseClazz(name);
    if (debug === true) {
      permit.debugOn();
    }
    if (baseObj != null && toString$.call(baseObj).slice(8, -1) === 'Function') {
      baseObj = baseObj();
    }
    if (toString$.call(baseObj).slice(8, -1) === 'Object') {
      permit = permit.use(baseObj);
    }
    return permit.init();
  };
}).call(this);
