// Generated by LiveScript 1.2.0
(function(){
  var requires, _, lo, Permit;
  requires = require('../../requires');
  _ = require('prelude-ls');
  lo = require('lodash');
  Permit = requires.lib('permit');
  module.exports = function(baseClazz, name, baseObj, debug){
    var permit;
    if (_.isType('String', baseClazz)) {
      baseObj = name;
      name = baseClazz;
      baseClazz = Permit;
    }
    permit = new baseClazz(name);
    if (debug === true) {
      permit.debugOn();
    }
    if (baseObj != null && _.isType('Function', baseObj)) {
      baseObj = baseObj();
    }
    if (_.isType('Object', baseObj)) {
      permit = permit.use(baseObj);
    }
    return permit.init();
  };
}).call(this);
