// Generated by LiveScript 1.2.0
(function(){
  var requires;
  requires = require('./requires');
  module.exports = {
    Authorizer: requires.lib('authorizer'),
    Ability: requires.lib('ability'),
    Allower: requires.lib('allower'),
    CachedAbility: requires.ability('cached_ability'),
    Permit: requires.lib('permit'),
    RulesLoader: requires.permit('permit_rules_loader'),
    DbRulesLoader: requires.permit('permit_rules_db_loader'),
    permitFor: requires.permit('permit-for')
  };
}).call(this);
