// Generated by LiveScript 1.2.0
(function(){
  var MatchesProcessor;
  module.exports = MatchesProcessor = (function(){
    MatchesProcessor.displayName = 'MatchesProcessor';
    var prototype = MatchesProcessor.prototype, constructor = MatchesProcessor;
    function MatchesProcessor(permit){
      this.permit = permit;
      this.compiledList = this.permit.compiledList;
    }
    prototype.process = function(key, value){
      this.key = key;
      this.value = value;
      return this.addCompiledMatch;
    };
    prototype.addCompiledMatch = function(){
      return this.compiledList.push(this.compile());
    };
    prototype.compile = function(){
      return this.compiler.compile(this.key, this.value);
    };
    prototype.compiler = function(){
      return new MatchCompiler(this);
    };
    return MatchesProcessor;
  }());
}).call(this);
