// Generated by LiveScript 1.2.0
(function(){
  var requires, User, Book, RepoExtractor, expect;
  requires = require('../../../requires');
  requires.test('test_setup');
  User = requires.fix('user');
  Book = requires.fix('book');
  RepoExtractor = requires.lib('rule').RepoExtractor;
  expect = require('chai').expect;
  describe('RepoRegistrator', function(){
    var accessRequest, rule, repo, book, can, cannot, createExtr;
    createExtr = function(container, action, subjects){
      return new RepoExtractor(container, action, subjects);
    };
    describe('create', function(){
      describe('invalid', function(){
        return specify('throws', function(){
          return expect(function(){
            return createExtr({}, 'ax');
          }).to['throw'];
        });
      });
      return describe('valid', function(){});
    });
    return context('valid extractor', function(){
      return before(function(){
        return repo = createRepo('my repo');
      });
    });
  });
}).call(this);
