// Generated by LiveScript 1.2.0
(function(){
  var RuleApplier, RuleRepo, rules;
  RuleApplier = requires.rule('apply').DynamicRulesApplier;
  RuleRepo = requires.rule('repo').RuleRepo;
  rules = requires.fixRules('rules');
}).call(this);
