// Generated by LiveScript 1.2.0
(function(){
  var requires, Book, User, Permit, permitFor, PermitMatcher, PermitRegistry, setup, createUser, createRequest, createPermit;
  requires = require('../../../../../requires');
  requires.test('test_setup');
  Book = requires.fix('book');
  User = requires.fix('user');
  Permit = requires.lib('permit');
  permitFor = requires.permit('factory').permitFor;
  PermitMatcher = requires.permit('matcher').UsePermitMatcher;
  PermitRegistry = requires.permit('registry').PermitRegistry;
  setup = requires.fix('permits').setup;
  createUser = requires.fac('create-user');
  createRequest = requires.fac('create-request');
  createPermit = requires.fac('create-permit');
  describe('PermitMatcher', function(){
    var permitMatcher, book, users, permits, requests, matching, noneMatching;
    users = {};
    permits = {};
    requests = {};
    matching = {};
    noneMatching = {};
    before(function(){
      users.kris = createUser.kris();
      users.emily = createUser.emily();
      requests.user = {
        user: users.kris
      };
      permits.user = setup.userPermit();
      return permitMatcher = new PermitMatcher(permits.user, requests.user);
    });
    describe('exclude', function(){
      describe('excludes user.name: kris', function(){
        before(function(){
          return permits.user.excludes = {
            user: users.kris
          };
        });
        return specify('matches access-request on excludes intersect', function(){
          return permitMatcher.exclude().should.be['true'];
        });
      });
      describe('excludes empty {}', function(){
        before(function(){
          return permits.user.excludes = {};
        });
        return specify('matches access-request since empty excludes always intersect', function(){
          return permitMatcher.exclude().should.be['true'];
        });
      });
      return describe('excludes other user', function(){
        before(function(){
          return permits.user.excludes = {
            user: users.emily
          };
        });
        return specify('does NOT match access-request since NO excludes intersect', function(){
          return permitMatcher.exclude().should.be['false'];
        });
      });
    });
    return describe('custom-ex-match', function(){
      var subject, permitMatcher, book, users, permits, requests, matching, noneMatching;
      users = {};
      permits = {};
      requests = {};
      matching = {};
      noneMatching = {};
      before(function(){
        PermitRegistry.clearAll();
        requests.admin = {
          user: {
            role: 'admin'
          }
        };
        requests.ctx = {
          ctx: void 8
        };
        permits.exUser = setup.exUserPermit();
        matching.permitMatcher = new PermitMatcher(permits.exUser, requests.admin);
        return noneMatching.permitMatcher = new PermitMatcher(permits.exUser, requests.ctx);
      });
      specify('matches access-request using permit.ex-match', function(){
        return matching.permitMatcher.customExMatch().should.be['true'];
      });
      specify('does NOT match access-request since permit.match does NOT match', function(){
        return noneMatching.permitMatcher.customExMatch().should.be['false'];
      });
      return describe('invalid ex-match method', function(){
        before(function(){
          return permits.invalidExUser = setup.invalidExUser();
        });
        return specify('should throw error', function(){
          return function(){
            return noneMatching.permitMatcher.customExMatch;
          }.should['throw'];
        });
      });
    });
  });
}).call(this);
