// Generated by LiveScript 1.2.0
(function(){
  var requires, Book, User, Permit, permitFor, PermitMatcher, PermitRegistry, setup, createUser, createRequest, createPermit;
  requires = require('../../../requires');
  requires.test('test_setup');
  Book = requires.fix('book');
  User = requires.fix('user');
  Permit = requires.lib('permit');
  permitFor = requires.permit('permit-for');
  PermitMatcher = requires.permit('permit_matcher');
  PermitRegistry = requires.permit('permit-registry');
  setup = require('./permits').setup;
  createUser = requires.fac('create-user');
  createRequest = requires.fac('create-request');
  createPermit = requires.fac('create-permit');
  describe('PermitMatcher', function(){
    var permitMatcher, book, users, permits, requests, matching, noneMatching;
    users = {};
    permits = {};
    requests = {};
    matching = {};
    noneMatching = {};
    before(function(){
      users.kris = createUser.kris;
      requests.user = {
        user: users.kris
      };
      permits.user = setup.userPermit();
      return permitMatcher = new PermitMatcher(permits.user, requests.user);
    });
    return describe('include', function(){
      describe('includes user.name: kris', function(){
        before(function(){
          return permits.user.includes = {
            user: users.kris
          };
        });
        return specify('matches access-request on includes intersect', function(){
          return permitMatcher.include().should.be['true'];
        });
      });
      describe('includes empty {}', function(){
        before(function(){
          return permits.user.includes = {};
        });
        return specify('matches access-request since empty includes always intersect', function(){
          return permitMatcher.include().should.be['true'];
        });
      });
      return describe('includes is nil', function(){
        before(function(){
          return permits.user.includes = void 8;
        });
        return specify('does NOT match access-request since NO includes intersect', function(){
          return permitMatcher.include().should.be['false'];
        });
      });
    });
  });
}).call(this);
