// Generated by LiveScript 1.2.0
(function(){
  var util, Debugger, RuleCleaner, toString$ = {}.toString;
  util = require('../../util');
  Debugger = util.Debugger;
  module.exports = RuleCleaner = (function(){
    RuleCleaner.displayName = 'RuleCleaner';
    var prototype = RuleCleaner.prototype, constructor = RuleCleaner;
    importAll$(prototype, arguments[0]);
    function RuleCleaner(container){
      this.container = container;
      this._validate();
      this;
    }
    prototype._type = 'RuleCleaner';
    prototype._validate = function(){
      if (toString$.call(this.container).slice(8, -1) !== 'Object') {
        throw Error("Container must be an Object, was: " + this.container);
      }
    };
    prototype.cleanAll = function(){
      this.clean('can');
      this.clean('cannot');
      return this;
    };
    prototype.clean = function(act){
      if (act === undefined) {
        return this.cleanAll();
      }
      if (!(act === 'can' || act === 'cannot')) {
        throw Error("Repo can only clear 'can' or 'cannot' rules, was: " + act);
      }
      this.debug('clean', act);
      this.container[act] = {};
      return this;
    };
    return RuleCleaner;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
