// Generated by LiveScript 1.2.0
(function(){
  var util, Debugger, RepoCleaner;
  util = require('../../util');
  Debugger = util.Debugger;
  module.exports = RepoCleaner = (function(){
    RepoCleaner.displayName = 'RepoCleaner';
    var prototype = RepoCleaner.prototype, constructor = RepoCleaner;
    importAll$(prototype, arguments[0]);
    function RepoCleaner(container){
      this.container = container;
    }
    prototype.cleanAll = function(){
      this.clean('can');
      this.clean('cannot');
      return this;
    };
    prototype.clearAll = function(){
      return this.cleanAll();
    };
    prototype.clean = function(act){
      if (act === undefined) {
        return this.cleanAll();
      }
      if (!(act === 'can' || act === 'cannot')) {
        throw Error("Repo can only clear 'can' or 'cannot' rules, was: " + act);
      }
      this.debug('clean', act);
      this.repo[act + "Rules"] = {};
      return this;
    };
    prototype.clear = function(act){
      return this.clean(act);
    };
    return RepoCleaner;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
