// Generated by LiveScript 1.2.0
(function(){
  var util, Debugger, RuleExtractor, RuleAdder;
  util = require('../../util');
  Debugger = util.Debugger;
  RuleExtractor = require('./rule_extractor');
  module.exports = RuleAdder = (function(){
    RuleAdder.displayName = 'RuleAdder';
    var prototype = RuleAdder.prototype, constructor = RuleAdder;
    importAll$(prototype, arguments[0]);
    function RuleAdder(container, action, subjects){
      this.container = container;
      this.action = action;
      this.subjects = subjects;
    }
    prototype.add = function(){
      this.debug('add rule', this.action, this.subjects);
      this.actionSubjects(this.action, this.subjects);
      this.container[this.action] = this.actionSubjects();
      this.addManage();
      return this;
    };
    prototype.actionSubjects = function(){
      return this._actionSubjects || (this._actionSubjects = this.extractor(this.container, this.action, this.subjects).extract());
    };
    prototype.addManage = function(){
      var i$, ref$, len$, action;
      if (this.action !== 'manage') {
        return;
      }
      this.debug('add-manage', this.action);
      for (i$ = 0, len$ = (ref$ = this.manageActions).length; i$ < len$; ++i$) {
        action = ref$[i$];
        this.container[action] = this.actionSubjects();
      }
      return this;
    };
    prototype.extractor = function(){
      return new RuleExtractor(this.container, this.action, this.subjects);
    };
    prototype.manageActions = require('../../util').globals.manageActions;
    return RuleAdder;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
