// Generated by LiveScript 1.2.0
(function(){
  var lo, authorize, Permit, permitFor, Book, book, GuestUser, guestUser, guestPermit, Ability, user, ability, aBook, currentUser, currentAbility, userCan, userCannot, readBook;
  lo = require('lodash');
  authorize = require('permit-authorize');
  Permit = authorize.Permit;
  permitFor = authorize.permitFor;
  Book = (function(superclass){
    var prototype = extend$((import$(Book, superclass).displayName = 'Book', Book), superclass).prototype, constructor = Book;
    function Book(obj){
      Book.superclass.apply(this, arguments);
    }
    return Book;
  }(Base));
  book = new Book({
    title: title
  });
  GuestUser = (function(superclass){
    var prototype = extend$((import$(GuestUser, superclass).displayName = 'GuestUser', GuestUser), superclass).prototype, constructor = GuestUser;
    function GuestUser(obj){
      GuestUser.superclass.apply(this, arguments);
    }
    prototype.role = 'guest';
    return GuestUser;
  }(User));
  guestUser = new GuestUser({
    name: 'unknown'
  });
  guestPermit = permitFor('guest', {
    match: function(access){
      return this.matches(access).user({
        role: 'guest'
      });
    },
    rules: {
      ctx: {
        area: {
          guest: function(){
            return this.ucan('publish', 'Paper');
          },
          admin: function(){
            return this.ucannot('publish', 'Paper');
          }
        }
      },
      read: function(){
        return this.ucan('read', 'Book');
      },
      write: function(){
        return this.ucan('write', 'Book');
      },
      'default': function(){
        return this.ucan('read', 'any');
      }
    }
  });
  Ability = authorize.Ability;
  user = function(name){
    return new User(name);
  };
  book = function(title){
    return new Book(title);
  };
  ability = function(user){
    return new Ability(user);
  };
  aBook = book('some book');
  currentUser = user('kris');
  currentAbility = ability(currentUser);
  userCan = function(accessRequest){
    return currentAbility.can(accessRequest);
  };
  userCannot = function(accessRequest){
    return currentAbility.cannot(accessRequest);
  };
  readBook = function(user, book){};
  if (userCan({
    action: 'read',
    subject: aBook
  })) {
    readBook(currentUser, aBook);
  }
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
