// Generated by LiveScript 1.2.0
(function(){
  var requires, Book, AccessRequest, fingerprint, FingerPrinter;
  requires = require('../../../../requires');
  requires.test('test_setup');
  Book = requires.fix('book');
  AccessRequest = requires.lib('access-request').AccessRequest;
  fingerprint = requires.lib('access-request').fingerprint;
  FingerPrinter = fingerprint.FingerPrinter;
  describe('Fingerprints', function(){
    var accessRequest, fingerPrinter;
    fingerPrinter = function(ar, debug){
      debug == null && (debug = true);
      return new FingerPrinter(ar, debug);
    };
    before(function(){
      return accessRequest = {
        user: {
          name: 'Kris'
        },
        action: 'read'
      };
    });
    return describe('fingerprint', function(){
      return specify('has method access-hash', function(){
        return fingerPrinter(accessRequest).fingerprint().should.not.eql(void 8);
      });
    });
  });
}).call(this);
