// Generated by LiveScript 1.2.0
(function(){
  var requires, Book, AccessRequest, fingerprint, FingerPrinter;
  requires = require('../../../../requires');
  requires.test('test_setup');
  Book = requires.fix('book');
  AccessRequest = requires.lib('access-request').AccessRequest;
  fingerprint = requires.lib('access-request').fingerprint;
  FingerPrinter = fingerprint.ObjectFingerPrint;
  describe('ObjectFingerPrint', function(){
    var accessRequest, fingerPrinter;
    accessRequest = {};
    fingerPrinter = function(ar, debug){
      debug == null && (debug = true);
      return new FingerPrinter(ar, debug);
    };
    before(function(){
      accessRequest.simple = {
        subject: 'Book'
      };
      accessRequest.advanced = {
        subject: 'Book',
        fingerprint: function(){
          return 'book';
        }
      };
      return accessRequest.hash = {
        subject: 'Book',
        hash: function(){
          return 'a book';
        }
      };
    });
    return describe('fingerprint', function(){
      specify('makes a fingerprint', function(){
        var res;
        res = fingerPrinter(accessRequest.simple).fingerprint();
        return res.should.eql("{\"subject\":\"Book\"}");
      });
      context('object has its own fingerprint method', function(){
        return specify('uses object fingerprint function', function(){
          var res;
          res = fingerPrinter(accessRequest.advanced).fingerprint();
          return res.should.eql("book");
        });
      });
      return context('object has its own hash method', function(){
        return specify('uses object hash function', function(){
          var res;
          res = fingerPrinter(accessRequest.hash).fingerprint();
          return res.should.eql("a book");
        });
      });
    });
  });
}).call(this);
