// Generated by LiveScript 1.2.0
(function(){
  var requires, lo, AbilityCache;
  requires = require('../../requires');
  lo = requires.util('lodash-lite');
  module.exports = AbilityCache = (function(){
    AbilityCache.displayName = 'AbilityCache';
    var prototype = AbilityCache.prototype, constructor = AbilityCache;
    function AbilityCache(){}
    return AbilityCache;
  }());
}).call(this);
