// Generated by LiveScript 1.2.0
(function(){
  var lo, AbilityCache;
  lo = requires('../util/lodash_lite');
  module.exports = AbilityCache = (function(){
    AbilityCache.displayName = 'AbilityCache';
    var prototype = AbilityCache.prototype, constructor = AbilityCache;
    function AbilityCache(){}
    return AbilityCache;
  }());
}).call(this);
