// Generated by LiveScript 1.2.0
(function(){
  var requires, lo, Debugger, recurse, valid_rules, RuleApplier, toString$ = {}.toString;
  requires = require('../../requires');
  lo = require('lodash');
  Debugger = requires.lib('debugger');
  recurse = function(key, val, ctx){
    switch (toString$.call(val).slice(8, -1)) {
    case 'Function':
      return val.call(ctx);
    case 'Object':
      return _.each(val, recurse, ctx);
    }
  };
  valid_rules = function(rules){
    return _.isType('Object', rules) || _.isType('Function', rules);
  };
  module.exports = RuleApplier = (function(){
    RuleApplier.displayName = 'RuleApplier';
    var prototype = RuleApplier.prototype, constructor = RuleApplier;
    importAll$(prototype, arguments[0]);
    function RuleApplier(repo, rules, accessRequest, debugging){
      this.repo = repo;
      this.rules = rules;
      this.accessRequest = accessRequest;
      this.debugging = debugging;
      if (!_.isType('Object', this.repo)) {
        throw Error("RuleApplier must be passed a RuleRepo, was: " + this.repo);
      }
      if (!valid_rules(this.rules)) {
        throw Error("RuleApplier must be passed the rules to be applied, was: " + this.rules);
      }
      if (!(this.accessRequest === undefined || _.isType('Object', this.accessRequest))) {
        throw Error("AccessRequest must be an Object, was: " + this.accessRequest);
      }
      this.debugging = this.debugging;
    }
    prototype.action = function(){
      var ref$;
      return (ref$ = this.accessRequest) != null ? ref$.action : void 8;
    };
    prototype.user = function(){
      var ref$;
      return (ref$ = this.accessRequest) != null ? ref$.user : void 8;
    };
    prototype.subject = function(){
      var ref$;
      return (ref$ = this.accessRequest) != null ? ref$.subject : void 8;
    };
    prototype.ctx = function(){
      var ref$;
      return (ref$ = this.accessRequest) != null ? ref$.ctx : void 8;
    };
    prototype.canRules = function(){
      return this.repo.canRules;
    };
    prototype.cannotRules = function(){
      return this.repo.cannotRules;
    };
    prototype.applyRulesFor = function(name, context){
      var rules, namedRules;
      this.debug("apply rules for " + name + " in context: " + context);
      if (_.isType('Object', name)) {
        this.applyObjRulesFor(name, context);
      }
      if (!_.isType('String', name)) {
        this.debug("Name to apply rules for must be a String, was: " + typeof name + " : " + name);
        return this;
      }
      rules = this.contextRules(context);
      namedRules = rules[name];
      if (_.isType('Function', namedRules)) {
        namedRules.call(this, this.accessRequest);
      } else {
        this.debug("rules key for " + name + " should be a function that resolves one or more rules");
      }
      return this;
    };
    prototype.applyObjRulesFor = function(obj, context){
      var rules, objKeys, self;
      rules = this.contextRules(context);
      this.debug('apply-obj-rules-for', obj, context, rules);
      objKeys = _.keys(obj);
      if (obj.clazz === 'User') {
        objKeys = ['name', 'role'];
      }
      self = this;
      return objKeys.each(function(key){
        var val, keyRules;
        val = obj[key];
        if (obj.clazz === 'User') {
          self.applyRulesFor(val, context);
        }
        keyRules = rules[key];
        return self.applyRulesFor(val, keyRules);
      });
    };
    prototype.contextRules = function(context){
      if (_.isType('Object', context)) {
        return context;
      }
      if (!_.isType('String', context)) {
        return this.rules;
      }
      if (_.isType('Object', this.rules[context])) {
        return this.rules[context];
      } else {
        this.debug("no such rules context: " + context, this.rules);
        return this.rules;
      }
    };
    prototype.applyActionRules = function(){
      this.applyRulesFor(this.action());
      this.applyRulesFor(this.action(), 'action');
      return this;
    };
    prototype.applyUserRules = function(){
      this.applyRulesFor(this.user());
      this.applyRulesFor(this.user(), 'user');
      return this;
    };
    prototype.applySubjectRules = function(){
      this.applyRulesFor(this.subject());
      this.applyRulesFor(this.subject(), 'subject');
      return this;
    };
    prototype.applyCtxRules = function(){
      this.applyRulesFor(this.ctx());
      this.applyRulesFor(this.ctx(), 'ctx');
      this.applyRulesFor(this.ctx(), 'context');
      return this;
    };
    prototype.applyContextRules = function(){
      return this.applyCtxRules();
    };
    prototype.validRequest = function(){
      return !lo.isEmpty(this.accessRequest);
    };
    prototype.applyDefaultRules = function(){
      this.debug('apply-default-rules', this.accessRequest, this.validRequest());
      if (_.isType('Object', this.accessRequest) && this.validRequest()) {
        this.applyAccessRules();
      } else {
        this.applyRulesFor('default');
      }
      return this;
    };
    prototype.applyRules = function(){
      if (!valid_rules(this.rules)) {
        this.debug('invalid permit rules could not be applied');
        return;
      }
      this.debug('applying rules', this.rules, 'for', this.accessRequest);
      switch (typeof this.rules) {
      case 'function':
        this.rules();
        break;
      case 'object':
        this.applyDefaultRules();
        break;
      default:
        throw Error("rules must be a Function or an Object, was: " + this.rules);
      }
      return this;
    };
    prototype.applyAccessRules = function(){
      this.debug('apply access rules on', this.accessRequest);
      this.applyActionRules();
      this.applyUserRules();
      this.applyCtxRules();
      return this;
    };
    prototype.applyAllRules = function(){
      var rules, ctx, self;
      switch (typeof this.rules) {
      case 'object':
        rules = this.rules;
        ctx = this;
        self = this;
        lo.each(_.keys(rules), function(key){
          return self.recurse(key, rules[key], ctx);
        });
        break;
      default:
        throw Error("rules must be an Object was: " + typeof this.rules);
      }
      return this;
    };
    prototype.ucan = function(actions, subjects, ctx){
      return this.repo.registerRule('can', actions, subjects, ctx);
    };
    prototype.ucannot = function(actions, subjects, ctx){
      return this.repo.registerRule('cannot', actions, subjects, ctx);
    };
    return RuleApplier;
  }(Debugger));
  lo.extend(RuleApplier, Debugger);
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
