// Generated by LiveScript 1.2.0
(function(){
  var toString$ = {}.toString;
  module.exports = {
    recurse: function(val, ctx, accessRequest){
      var k, results$ = [];
      switch (toString$.call(val).slice(8, -1)) {
      case 'Function':
        return val.call(ctx, accessRequest);
      case 'Object':
        for (k in val) {
          results$.push(recurse(k, ctx, accessRequest));
        }
        return results$;
      }
    },
    validRules: function(rules){
      return toString$.call(rules).slice(8, -1) === 'Object' || toString$.call(rules).slice(8, -1) === 'Function';
    }
  };
}).call(this);
