// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    debugging: false,
    debug: function(msg){
      if (this.debugging) {
        console.log(this.constructor.displayName + ':');
        return console.log.apply(this, arguments);
      }
    },
    debugOn: function(){
      return this.debugging = true;
    },
    debugOff: function(){
      return this.debugging = false;
    }
  };
}).call(this);
