// Generated by LiveScript 1.2.0
(function(){
  module.exports = function(){
    var newmap;
    ({
      sort_object: function(map){
        var keys;
        return keys = _.sortBy(_.keys(map), function(a){
          return a;
        });
      }
    });
    newmap = {};
    _.each(keys, function(k){
      return newmap[k] = map[k];
    });
    return newmap;
  };
}).call(this);
