// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    debugging: false,
    debug: function(msg){
      var id;
      if (this.debugging) {
        id = this.constructor.displayName;
        if (this._last_time_id === id) {
          console.timeEnd(id);
        }
        this._last_time_id = id;
        console.time(id);
        console.log(id + ':');
        return console.log.apply(this, arguments);
      }
    },
    debugOn: function(){
      return this.debugging = true;
    },
    debugOff: function(){
      return this.debugging = false;
    }
  };
}).call(this);
