// Generated by LiveScript 1.2.0
(function(){
  var time;
  time = require('./time');
  module.exports = {
    debugging: false,
    debug: function(msg){
      if (this.debugging) {
        console.log(this.constructor.displayName + ':');
        return console.log.apply(this, arguments);
      }
    },
    debugOn: function(){
      this.debugging = true;
      return this;
    },
    timerOn: function(methods){
      time.timer(this, {
        only: methods,
        except: [/debug.*/]
      });
      return this;
    },
    debugOff: function(){
      this.debugging = false;
      return this;
    }
  };
}).call(this);
