// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    wildcards: ['Any', 'any', '*'],
    classKeys: ['clazz', '_clazz', '_class', '$clazz', '$class'],
    manageActions: ['create', 'delete', 'update', 'edit']
  };
}).call(this);
