// Generated by LiveScript 1.2.0
(function(){
  var camelCase;
  camelCase = function(s){
    return (s || '').toLowerCase().replace(/(\b|-)\w/g, function(m){
      return m.toUpperCase().replace(/-/, '');
    });
  };
  module.exports = {
    camelCase: camelCase,
    camelize: camelCase
  };
}).call(this);
