// Generated by LiveScript 1.2.0
(function(){
  var toString$ = {}.toString;
  module.exports = function(subject){
    this.subject = subject;
    return {
      clazz: function(){
        return camelCase(this.findClass || '');
      },
      findClass: function(){
        var res;
        return res = (function(){
          switch (toString$.call(this.subject).slice(8, -1)) {
          case 'Object':
            return this.objectClass();
          case 'String':
            return this.subject();
          }
        }.call(this));
      },
      instance: function(){
        return this._instance || (this._instance = this.getInstance() || {});
      },
      getInstance: function(){
        if (this.oneKey()) {
          return this.outerValue();
        } else {
          return this.subject;
        }
      },
      outerValue: function(){
        return this.subject[this.firstKey()];
      },
      oneKey: function(){
        return Object.keys(this.subject).length === 1;
      },
      objectClass: function(){
        if (this.oneKey()) {
          return this.outerClass();
        } else {
          return this.innerClass();
        }
      },
      firstKey: function(){
        return Object.keys(this.subject)[0];
      },
      outerClass: function(){
        return this.firstKey();
      },
      innerClass: function(){
        if (subject.constructor.displayName) {
          return subject.constructor.displayName;
        }
        return subject.clazz || subject._clazz || subject.$clazz || subject._class || subject.$class;
      }
    };
  };
}).call(this);
