// Generated by LiveScript 1.2.0
(function(){
  var ObjectFingerprint, ArrayFingerprint, join, FingerPrinter;
  ObjectFingerprint = require('./object_fingerprint');
  ArrayFingerprint = require('./array_fingerprint');
  join = require('../../util').array.join;
  module.exports = FingerPrinter = (function(){
    FingerPrinter.displayName = 'FingerPrinter';
    var prototype = FingerPrinter.prototype, constructor = FingerPrinter;
    function FingerPrinter(ar){
      this.ar = ar;
    }
    prototype.fingerprint = function(){
      return this.accessHash();
    };
    prototype.accessHash = function(){
      return this._accessHash || (this._accessHash = [this.actionHash(), this.subjectHash(), this.ctxHash()].join(':'));
    };
    prototype.subjectHash = function(){
      return this.subjectFingerprint || (this.subjectFingerprint = new ObjectFingerprint(this.ar.subject).fingerprint());
    };
    prototype.actionHash = function(){
      return this.actionFingerprint || (this.actionFingerprint = new ArrayFingerprint(this.ar.action).fingerprint());
    };
    prototype.userHash = function(){
      return this.userFingerprint || (this.userFingerprint = new ObjectFingerprint(this.ar.user).fingerprint());
    };
    prototype.ctxHash = function(){
      return this.ctxFingerprint || (this.ctxFingerprint = new ObjectFingerprint(this.ar.ctx).fingerprint());
    };
    return FingerPrinter;
  }());
}).call(this);
