// Generated by LiveScript 1.2.0
(function(){
  var Debugger, CompiledMatcher, toString$ = {}.toString;
  Debugger = require('../../util').Debugger;
  module.exports = CompiledMatcher = (function(){
    CompiledMatcher.displayName = 'CompiledMatcher';
    var prototype = CompiledMatcher.prototype, constructor = CompiledMatcher;
    importAll$(prototype, arguments[0]);
    function CompiledMatcher(context, debugging){
      this.context = context;
      this.debugging = debugging;
      this.compiledList = this.context.compiledList;
    }
    prototype.matchCompiled = function(){
      var res, i$, ref$, len$, matchFun;
      this.debug("match-compiled");
      if (toString$.call(this.compiledList).slice(8, -1) !== 'Array') {
        return false;
      }
      this.debug("compiled matchers: " + this.compiledList.length);
      res = false;
      for (i$ = 0, len$ = (ref$ = this.compiledList).length; i$ < len$; ++i$) {
        matchFun = ref$[i$];
        if (matchFun(this.accessRequest)) {
          break;
        }
      }
      return res;
    };
    return CompiledMatcher;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
