// Generated by LiveScript 1.2.0
(function(){
  var AccessMatcher, ContextMatcher, IncludeMatcher, toString$ = {}.toString;
  AccessMatcher = require('../../access_request').matcher.AccessMatcher;
  ContextMatcher = require('./context_matcher');
  module.exports = IncludeMatcher = (function(superclass){
    var prototype = extend$((import$(IncludeMatcher, superclass).displayName = 'IncludeMatcher', IncludeMatcher), superclass).prototype, constructor = IncludeMatcher;
    function IncludeMatcher(context, accessRequest, debugging){
      this.accessRequest = accessRequest;
      this.debugging = debugging;
      IncludeMatcher.superclass.call(this, context, constructor.defaultKey, this.debugging);
    }
    IncludeMatcher.defaultKey = 'includes';
    prototype.match = function(){
      console.log(this);
      this.debug('match', this.matchContext);
      return this.include() || this.inMatch();
    };
    prototype.include = function(){
      if (toString$.call(this.matchContext).slice(8, -1) !== 'Object') {
        return false;
      }
      this.debug('intersect', this.matchContext, this.accessRequest);
      return this.intersectOn(this.accessRequest);
    };
    prototype.inMatch = function(){
      var res;
      if (toString$.call(this.matchContext).slice(8, -1) !== 'Function') {
        return false;
      }
      res = this.matchContext(this.accessRequest);
      this.debug('custom-match', this.permit.match, res);
      if (res.constructor === AccessMatcher) {
        return res.result();
      }
      if (res === undefined) {
        return false;
      }
      if (toString$.call(res).slice(8, -1) !== 'Boolean') {
        throw Error(this.key + " method of context " + this.context.name + " must return a Boolean value, was: " + toString$.call(res).slice(8, -1));
      }
      return res;
    };
    return IncludeMatcher;
  }(ContextMatcher));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
