// Generated by LiveScript 1.2.0
(function(){
  var Intersect, AccessMatcher, Debugger, PermitMatcher;
  Intersect = require('../../util').Intersect;
  AccessMatcher = require('../../access_request').matcher.AccessMatcher;
  Debugger = require('../../util').Debugger;
  module.exports = PermitMatcher = (function(){
    PermitMatcher.displayName = 'PermitMatcher';
    var prototype = PermitMatcher.prototype, constructor = PermitMatcher;
    importAll$(prototype, arguments[0]);
    function PermitMatcher(context, accessRequest, debugging){
      this.context = context;
      this.accessRequest = accessRequest;
      this.debugging = debugging;
      this.validate();
      this.intersect = Intersect();
    }
    prototype.match = function(options){
      var res, mc;
      options == null && (options = {});
      this.debug('permit-matcher match');
      res = this.include() && !this.exclude();
      if (options.compiled === false) {
        return res;
      }
      this.debug('compiled result:', this.matchCompiled());
      mc = this.matchCompiled();
      this.debug('match compiled', mc);
      return res || mc;
    };
    prototype.include = function(){
      return this.includeMatcher().match();
    };
    prototype.exclude = function(){
      return this.includeMatcher().match();
    };
    prototype.includeMatcher = function(){
      return this._includeMatcher || (this._includeMatcher = new IncludeMatcher(this.context, this.accessRequest, this.debugging));
    };
    prototype.excludeMatcher = function(){
      return this._excludeMatcher || (this._excludeMatcher = new ExcludeMatcher(this.context, this.accessRequest, this.debugging));
    };
    prototype.validate = function(){
      if (!this.context) {
        throw Error("PermitMatcher missing permit");
      }
      if (this.accessRequest != null && this.accessRequest === undefined) {
        throw Error("access-request is undefined");
      }
    };
    return PermitMatcher;
  }(Debugger));
  import$(PermitMatcher, Debugger);
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
