// Generated by LiveScript 1.2.0
(function(){
  var RulesAccessor, camelCase, Debugger, StaticApplier, DynamicApplier, PermitRuleApplier, toString$ = {}.toString;
  RulesAccessor = require('../../rule').RulesAccessor;
  camelCase = require('../../util').string.camelCase;
  Debugger = require('../../util').Debugger;
  StaticApplier = require('../../rule').apply.StaticApplier;
  DynamicApplier = require('../../rule').apply.StaticApplier;
  module.exports = PermitRuleApplier = (function(){
    PermitRuleApplier.displayName = 'PermitRuleApplier';
    var prototype = PermitRuleApplier.prototype, constructor = PermitRuleApplier;
    importAll$(prototype, arguments[0]);
    function PermitRuleApplier(ctx, accessRequest, debugging){
      this.ctx = ctx;
      this.accessRequest = accessRequest;
      this.debugging = debugging != null ? debugging : true;
      this._validate();
      this.appliedRules = false;
      this.debug('ctx', this.ctx);
      this.rules = this.ctx.rules;
      this.debug('rules', this.rules);
      this;
    }
    prototype._validate = function(){
      if (toString$.call(this.ctx).slice(8, -1) !== 'Object') {
        throw Error("Apply Context must be an Object, was: " + this.cxt);
      }
      if (!this.ctx.repo) {
        throw Error("Apply Context missing a .repo to store the applied rules, was: " + this.cxt);
      }
    };
    prototype.clean = function(){
      return this.appliedRules = false;
    };
    prototype.staticApplier = function(){
      return new StaticApplier(this.executionContext(), this.rules, this.debugging);
    };
    prototype.dynamicApplier = function(){
      return new DynamicApplier(this.executionContext(), this.rules, this.accessRequest, this.debugging);
    };
    prototype.executionContext = function(){
      return this._executer || (this._executer = this.ctx.repo());
    };
    prototype.ruleApplier = function(){
      return new this.rulesApplier.clazz(this.ctx, this.accessRequest, this.debugging);
    };
    prototype.validateAccessRequest = function(){
      if (toString$.call(this.accessRequest).slice(8, -1) !== 'Object') {
        throw Error("Invalid access request: " + this.accessRequest + ", must be an Object");
      }
    };
    prototype.applierFor = function(type){
      return this[type + "Applier"]();
    };
    prototype.apply = function(type, force){
      type == null && (type = 'static');
      return this["apply" + camelCase(type)](force);
    };
    prototype.applyDynamic = function(){
      return this.applierFor('dynamic').applyRules();
    };
    prototype.applyStatic = function(force){
      if (force) {
        this.debug('forcing static apply');
      }
      if (!(this.appliedRules && !force)) {
        this.debug('apply static rules');
        this.applierFor('static').applyRules();
        return this.appliedStaticRules = true;
      } else {
        return this.debug('static rules already applied before', this.appliedStaticRules);
      }
    };
    return PermitRuleApplier;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
