// Generated by LiveScript 1.2.0
(function(){
  var PermitContainer, toString$ = {}.toString;
  module.exports = PermitContainer = (function(){
    PermitContainer.displayName = 'PermitContainer';
    var prototype = PermitContainer.prototype, constructor = PermitContainer;
    function PermitContainer(name, desc){
      this.name = name;
      this.desc = desc;
      this.repo = {};
    }
    prototype.add = function(permit){
      this.repo[permit.name] = permit;
      permit.container = this;
      return this;
    };
    prototype.remove = function(thing){
      var name;
      name = thing;
      if (toString$.call(thing).slice(8, -1) === 'Object') {
        name = thing.name;
      }
      if (!this.repo[name]) {
        throw new Error("Permit Repo has no entry for: " + name);
      }
      return this.repo['delete'](name);
    };
    prototype.activate = function(){
      var active;
      active = true;
      return PermitContainer.add(this);
    };
    prototype.deactivate = function(){
      var active;
      active = false;
      return PermitContainer.remove(this);
    };
    PermitContainer.add = function(container){
      return this.activeContainers[container.name] = container;
    };
    PermitContainer.remove = function(container){
      return this.activeContainers['delete'](container.name);
    };
    PermitContainer.activeContainers = [];
    PermitContainer.activeContainersPermits = function(){
      return values(this.activeContainers);
    };
    PermitContainer.hasAny = function(){
      return this.activeContainers && this.activeContainers.index > 0;
    };
    return PermitContainer;
  }());
}).call(this);
