// Generated by LiveScript 1.2.0
(function(){
  var Debugger, MatchCompiler, MatchesOnCompiler, toString$ = {}.toString;
  Debugger = require('../../../util').Debugger;
  MatchCompiler = require('./match_compiler');
  module.exports = MatchesOnCompiler = (function(){
    MatchesOnCompiler.displayName = 'MatchesOnCompiler';
    var prototype = MatchesOnCompiler.prototype, constructor = MatchesOnCompiler;
    importAll$(prototype, arguments[0]);
    function MatchesOnCompiler(context, debugging){
      this.context = context;
      this.debugging = debugging;
      this.debug('context', this.context);
      this.matchesOn = this.context.matchesOn;
    }
    prototype.compile = function(){
      var key;
      this.debug("compile-matchers", this.matchesOn);
      if (toString$.call(this.matchesOn).slice(8, -1) !== 'Object') {
        return;
      }
      this.compiledList = [];
      this.debug("compile...");
      for (key in this.matchesOn) {
        this.addCompiled(this.compileFor(key));
      }
      this.debug('compiled matchers:', this.compiledList);
      return this.compiledList;
    };
    prototype.addCompiled = function(compiled){
      return this.compiledList.push(compiled);
    };
    prototype.compileFor = function(key){
      return this.matchCompiler().compile(key, this.matchesOn[key]);
    };
    prototype.matchCompiler = function(){
      return this._matchCompiler || (this._matchCompiler = new MatchCompiler(this.context));
    };
    return MatchesOnCompiler;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
