// Generated by LiveScript 1.2.0
(function(){
  var Debugger, MatchCompiler, toString$ = {}.toString;
  Debugger = require('../../../util').Debugger;
  module.exports = MatchCompiler = (function(){
    MatchCompiler.displayName = 'MatchCompiler';
    var prototype = MatchCompiler.prototype, constructor = MatchCompiler;
    importAll$(prototype, arguments[0]);
    function MatchCompiler(context){
      this.context = context;
      if (toString$.call(this.context).slice(8, -1) !== 'Object') {
        throw new Error("MatchCompiler requires an Object as the context");
      }
      if (!(this.context.matchOn && toString$.call(this.context.matchOn).slice(8, -1) === 'Function')) {
        throw new Error("MatchCompiler requires context to have a matchOn(access-request) function, was: " + this.context);
      }
    }
    prototype.compile = function(type, match){
      var context;
      this.type = type;
      this.match = match;
      this.debug("compile", this.type, this.match);
      context = this.context;
      return function(accessRequest){
        var matchObj, ref$;
        matchObj = (ref$ = {}, ref$[type] = this.match, ref$);
        return context.matchOn(accessRequest, matchObj);
      };
    };
    return MatchCompiler;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
