// Generated by LiveScript 1.2.0
(function(){
  var MatchesProcessor;
  module.exports = MatchesProcessor = (function(){
    MatchesProcessor.displayName = 'MatchesProcessor';
    var prototype = MatchesProcessor.prototype, constructor = MatchesProcessor;
    function MatchesProcessor(context){
      this.context = context;
      this.compiledList = [];
    }
    prototype.process = function(key, value){
      this.key = key;
      this.value = value;
      return this.compiler.compile(this.key, this.value);
    };
    prototype.compiler = function(){
      return new MatchCompiler(this.context);
    };
    return MatchesProcessor;
  }());
}).call(this);
