// Generated by LiveScript 1.2.0
(function(){
  var requires, Matcher, Permit, setup, createUser, createMatcher, intersect, excludes;
  requires = require('../../../../../requires');
  requires.test('test_setup');
  Matcher = requires.permit('matcher').ContextMatcher;
  Permit = requires.lib('permit').Permit;
  setup = requires.fix('permits').setup;
  createUser = requires.fac('create-user');
  createMatcher = function(ctx, ar, debug){
    debug == null && (debug = true);
    return new Matcher(ctx, ar, debug);
  };
  intersect = function(obj){
    return {
      intersect: obj
    };
  };
  excludes = function(obj){
    return intersect({
      includes: obj
    });
  };
  describe('PermitMatcher', function(){
    var matcher, book, users, permits, requests, matching, noneMatching;
    users = {};
    permits = {};
    requests = {};
    matching = {};
    noneMatching = {};
    before(function(){
      users.kris = createUser.kris();
      users.emily = createUser.emily();
      requests.user = {
        user: users.kris
      };
      return permits.user = setup.userPermit();
    });
    return describe('exclude', function(){
      describe('excludes user.name: kris', function(){
        beforeEach(function(){
          permits.user.excludes = {
            user: users.kris
          };
          return matcher = createMatcher(permits.user, requests.user);
        });
        return specify('matches access-request on excludes intersect', function(){
          return matcher.exclude().should.be['true'];
        });
      });
      describe('excludes empty {}', function(){
        beforeEach(function(){
          permits.user.excludes = {};
          return matcher = createMatcher(permits.user, requests.user);
        });
        return specify('matches access-request since empty excludes always intersect', function(){
          return matcher.exclude().should.be['true'];
        });
      });
      return describe('excludes other user', function(){
        beforeEach(function(){
          permits.user.excludes = {
            user: users.emily
          };
          return matcher = createMatcher(permits.user, requests.user);
        });
        return specify('does NOT match access-request since NO excludes intersect', function(){
          return matcher.exclude().should.be['false'];
        });
      });
    });
  });
}).call(this);
