// Generated by LiveScript 1.2.0
(function(){
  var Debugger, AccessRequest, Ability, Authorizer, toString$ = {}.toString;
  Debugger = require('../util').Debugger;
  AccessRequest = require('../access_request').AccessRequest;
  Ability = require('../ability').Ability;
  module.exports = Authorizer = (function(){
    Authorizer.displayName = 'Authorizer';
    var prototype = Authorizer.prototype, constructor = Authorizer;
    importAll$(prototype, arguments[0]);
    function Authorizer(user){
      this.user = user;
    }
    prototype.authorize = function(action, subject, ctx){
      var ref$;
      this.debug('authorize', action, subject, ctx);
      if (toString$.call(action).slice(8, -1) === 'Object') {
        ref$ = [obj.action, obj.subject, obj.context || obj.ctx], action = ref$[0], subject = ref$[1], ctx = ref$[2];
      }
      return this.can(action, subject, context);
    };
    prototype.abilityClazz = Ability;
    prototype.createAbility = function(){
      return new this.abilityClazz(this.user, this.debugging);
    };
    prototype.ability = function(){
      return this.currentAbility || (this.currentAbility = this.createAbility());
    };
    prototype.access = function(action, subject, ctx){
      var ar;
      ar = new AccessRequest(this.user, action, subject, ctx, this.debugging);
      if (this.debugging) {
        ar.debugOn();
      }
      return ar;
    };
    prototype.can = function(action, subject, context){
      this.debug('can', action, subject, context);
      return this.ability().can(this.access(action, subject, context));
    };
    prototype.cannot = function(action, subject, context){
      this.debug('cannot', action, subject, context);
      return this.ability().cannot(this.access(action, subject, context));
    };
    return Authorizer;
  }(Debugger));
  import$(Authorizer, Debugger);
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
