// Generated by LiveScript 1.2.0
(function(){
  var RepoGuardian;
  module.exports = RepoGuardian = (function(){
    RepoGuardian.displayName = 'RepoGuardian';
    var prototype = RepoGuardian.prototype, constructor = RepoGuardian;
    function RepoGuardian(ruleRepo){
      this.ruleRepo = ruleRepo;
    }
    prototype.permitAllower = function(){
      return this._permit_allower || (this._permit_allower = new PermitAllower(this.ruleRepo, this.debugging));
    };
    prototype.allows = function(accessRequest){
      return this.permitAllower().allows(accessRequest);
    };
    prototype.disallows = function(accessRequest){
      return this.permitAllower().disallows(accessRequest);
    };
    return RepoGuardian;
  }());
}).call(this);
