// Generated by LiveScript 1.2.0
(function(){
  var util, Debugger, RuleRegistrator, toString$ = {}.toString;
  util = require('../../util');
  Debugger = util.Debugger;
  module.exports = RuleRegistrator = (function(){
    RuleRegistrator.displayName = 'RuleRegistrator';
    var prototype = RuleRegistrator.prototype, constructor = RuleRegistrator;
    importAll$(prototype, arguments[0]);
    function RuleRegistrator(repo){
      this.repo = repo;
    }
    prototype.addRule = function(ruleContainer, action, subjects){
      var ruleSubjects, uniqueSubjects, actionSubjects, registeredActionSubjects, i$, ref$, len$, results$ = [];
      this.debug('add rule', action, subjects);
      if (toString$.call(ruleContainer).slice(8, -1) !== 'Object') {
        throw Error("Container must be an object");
      }
      ruleSubjects = ruleContainer[action] || [];
      subjects = normalize(subjects);
      ruleSubjects = ruleSubjects.concat(subjects);
      ruleSubjects = ruleSubjects.map(function(subject){
        var val;
        val = camelCase(subject);
        if (val === 'Any') {
          return '*';
        } else {
          return val;
        }
      });
      uniqueSubjects = unique(ruleSubjects);
      actionSubjects = ruleContainer[action];
      if (toString$.call(actionSubjects).slice(8, -1) !== 'Array') {
        actionSubjects = [];
      }
      registeredActionSubjects = this.registerActionSubjects(actionSubjects, uniqueSubjects);
      ruleContainer[action] = registeredActionSubjects;
      if (action === 'manage') {
        for (i$ = 0, len$ = (ref$ = this.manageActions()).length; i$ < len$; ++i$) {
          action = ref$[i$];
          results$.push(ruleContainer[action] = registeredActionSubjects);
        }
        return results$;
      }
    };
    prototype.registerActionSubjects = function(actionContainer, subjects){
      this.debug("register action subjects", actionContainer, subjects);
      return unique(actionContainer.concat(subjects));
    };
    prototype.registerRule = function(act, actions, subjects){
      var ruleContainer, i$, len$, action, results$ = [];
      actions = normalize(actions);
      ruleContainer = this.containerFor(act);
      this.debug('rule container', ruleContainer);
      for (i$ = 0, len$ = actions.length; i$ < len$; ++i$) {
        action = actions[i$];
        results$.push(this.addRule(ruleContainer, action, subjects));
      }
      return results$;
    };
    return RuleRegistrator;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
