// Generated by LiveScript 1.2.0
(function(){
  var requires, Matcher, expect;
  requires = require('../../../../../requires');
  requires.test('test_setup');
  Matcher = requires.rule('container').matcher.RuleSubjectMatcher;
  expect = require('chai').expect;
  describe('RuleSubjectMatcher', function(){
    var matcher, createMatcher;
    createMatcher = function(subjects, debug){
      debug == null && (debug = true);
      return new Matcher(subjects);
    };
    describe('create', function(){
      describe('invalid', function(){
        return specify('throws', function(){
          return expect(function(){
            return createMatcher(void 8).to['throw'];
          });
        });
      });
      return describe('valid', function(){
        return specify('ok', function(){
          return expect(function(){
            return createMatcher([]).to.not['throw'];
          });
        });
      });
    });
    return context('created', function(){
      return before(function(){
        return matcher = createMatcher('my matcher');
      });
    });
  });
}).call(this);
