// Generated by LiveScript 1.2.0
(function(){
  var requires, setup, Book, User, Permit, permitFor, PermitMatcher, PermitRegistry, createUser, createRequest, createPermit;
  requires = require('../../../requires');
  requires.test('test_setup');
  setup = require('./../permits').setup;
  Book = requires.fix('book');
  User = requires.fix('user');
  Permit = requires.lib('permit');
  permitFor = requires.permit('permit-for');
  PermitMatcher = requires.permit('permit_matcher');
  PermitRegistry = requires.permit('permit-registry');
  createUser = requires.fac('create-user');
  createRequest = requires.fac('create-request');
  createPermit = requires.fac('create-permit');
  describe('PermitMatcher', function(){
    var subject, permitMatcher, book, users, permits, requests, matching, noneMatching;
    users = {};
    permits = {};
    requests = {};
    matching = {};
    noneMatching = {};
    before(function(){
      users.kris = createUser.kris;
      users.emily = createUser.emily;
      requests.user = {
        user: users.kris
      };
      permits.user = setup.userPermit();
      return permitMatcher = new PermitMatcher(permits.user, requests.user);
    });
    return describe('custom-match', function(){
      before(function(){
        book = new Book({
          title: 'far and away'
        });
        requests.subject = {
          user: {},
          subject: book
        };
        requests.ctx = {
          ctx: void 8
        };
        permits.book = setup.bookPermit();
        matching.permitMatcher = new PermitMatcher(permits.book, requests.subject);
        return noneMatching.permitMatcher = new PermitMatcher(permits.book, requests.ctx);
      });
      context('matching permit-matcher', function(){
        before(function(){
          return subject = matching.permitMatcher;
        });
        specify('has permit', function(){
          return subject.permit.should.eql(permits.book);
        });
        return specify('has subject access-request', function(){
          return subject.accessRequest.should.eql(requests.subject);
        });
      });
      context('matching permit-matcher', function(){
        before(function(){
          return subject = noneMatching.permitMatcher;
        });
        specify('has permit', function(){
          return subject.permit.should.eql(permits.book);
        });
        return specify('has access-request', function(){
          return subject.accessRequest.should.eql(requests.ctx);
        });
      });
      specify('matches access-request using permit.match', function(){
        return matching.permitMatcher.customMatch().should.be['true'];
      });
      specify('does NOT match access-request since permit.match does NOT match', function(){
        return noneMatching.permitMatcher.customMatch().should.be['false'];
      });
      return describe('invalid match method', function(){
        before(function(){
          return permits.user = setup.invalidUser();
        });
        return specify('should throw error', function(){
          return function(){
            return noneMatching.permitMatcher.customMatch;
          }.should['throw'];
        });
      });
    });
  });
}).call(this);
