// Generated by LiveScript 1.2.0
(function(){
  var Book, toString$ = {}.toString;
  module.exports = Book = (function(){
    Book.displayName = 'Book';
    var prototype = Book.prototype, constructor = Book;
    function Book(obj){
      var key;
      this.obj = obj;
      if (toString$.call(this.obj).slice(8, -1) === 'Object') {
        for (key in this.obj) {
          this[key] = this.obj[key];
        }
      }
    }
    return Book;
  }());
}).call(this);
