// Generated by LiveScript 1.2.0
(function(){
  var lo, Book, toString$ = {}.toString;
  lo = require('lodash');
  module.exports = Book = (function(){
    Book.displayName = 'Book';
    var prototype = Book.prototype, constructor = Book;
    function Book(obj){
      var i$, ref$, len$, key;
      this.obj = obj;
      if (toString$.call(this.obj).slice(8, -1) === 'Object') {
        for (i$ = 0, len$ = (ref$ = lo.keys(this.obj)).length; i$ < len$; ++i$) {
          key = ref$[i$];
          this[key] = this.obj[key];
        }
      }
    }
    return Book;
  }());
}).call(this);
