// Generated by LiveScript 1.2.0
(function(){
  var User;
  module.exports = User = (function(){
    User.displayName = 'User';
    var prototype = User.prototype, constructor = User;
    function User(user){
      this.set(user);
    }
    prototype.set = function(user){
      var key, results$ = [];
      for (key in user) {
        results$.push(this[key] = user[key]);
      }
      return results$;
    };
    return User;
  }());
}).call(this);
