// Generated by LiveScript 1.2.0
(function(){
  module.exports = function(baseClazz, name, baseObj, debug){
    var pm;
    pm = new PermitFactory(baseClazz, name, baseObj, debug);
    return pm.create();
  };
}).call(this);
