// Generated by LiveScript 1.2.0
(function(){
  var PermitFactory;
  module.exports = PermitFactory = (function(){
    PermitFactory.displayName = 'PermitFactory';
    var prototype = PermitFactory.prototype, constructor = PermitFactory;
    function PermitFactory(x){
      this.x = x;
    }
    prototype.blip = function(){};
    return PermitFactory;
  }());
}).call(this);
