// Generated by LiveScript 1.2.0
(function(){
  var requires, deepExtend, createUser, createRequest;
  requires = require('../../../requires');
  deepExtend = require('deep-extend');
  createUser = requires.fac('create-permit');
  createRequest = requires.fac('create-request');
  module.exports = {
    empty: {},
    user: function(user){
      return createRequest.userAccess(user);
    },
    role: function(role){
      return createRequest.roleAccess('admin');
    },
    guest: function(){
      return this.role('guest');
    },
    admin: function(){
      return this.role('admin');
    },
    kris: {
      user: {
        name: 'kris'
      },
      action: 'read',
      ctx: {
        auth: true
      }
    },
    krisAdmin: deepExtend({}, this.admin, this.kris)
  };
}).call(this);
