// Generated by LiveScript 1.2.0
(function(){
  var requires, User, Book, RuleCleaner, expect;
  requires = require('../../../../requires');
  requires.test('test_setup');
  User = requires.fix('user');
  Book = requires.fix('book');
  RuleCleaner = requires.rule('repo').RuleCleaner;
  expect = require('chai').expect;
  describe('RepoCleaner', function(){
    var accessRequest, rule, repo, book, can, cannot, createRepo;
    createRepo = function(name, debug){
      return new RuleRepo(name, debug);
    };
    return context('basic repo', function(){
      return before(function(){
        return repo = createRepo('my repo');
      });
    });
  });
}).call(this);
