// Generated by LiveScript 1.2.0
(function(){
  var requires, string;
  requires = require('../../../requires');
  requires.test('test_setup');
  string = requires.util('string');
  describe('string_util', function(){
    return describe('camelCase', function(){
      return specify('camelized full upper case', function(){
        return string.camelCase('user-admin').should.eql('UserAdmin');
      });
    });
  });
}).call(this);
