// Generated by LiveScript 1.2.0
(function(){
  var requires, stringUtil, camelCase;
  requires = require('../../../requires');
  requires.test('test_setup');
  stringUtil = requires.util('string_util');
  camelCase = stringUtil.camelCase;
  describe('string_util', function(){
    return describe('camel-case', function(){
      return specify('camelized full upper case', function(){
        return camelCase('user-admin').should.eql('UserAdmin');
      });
    });
  });
}).call(this);
