// Generated by LiveScript 1.2.0
(function(){
  var timer, test, Aba, aba;
  timer = require('../../util').timer.timerOn;
  test = {
    abra: function(){
      return console.log('abra');
    },
    go: 0,
    x: function(){
      timerOn(this, {
        except: 'x'
      });
      return this;
    }
  };
  Aba = (function(){
    Aba.displayName = 'Aba';
    var prototype = Aba.prototype, constructor = Aba;
    function Aba(v){
      this.v = v;
    }
    prototype.blip = function(){
      return console.log('blip');
    };
    prototype.time = function(){
      timerOn(this, {
        except: 'time'
      });
      return this;
    };
    return Aba;
  }());
  aba = new Aba;
  aba.blip();
  aba.time().blip();
  test.x().abra();
}).call(this);
